import { Product } from './types/Products';

export const sampleProducts: Product[] = [
  {
    name: 'Ibanez J Custom RG8527',
    slug: 'ibanez-j-custom-rg8527',
    image: '../images/p1.jpg',
    brand: 'Ibanez',
    price: 2999.99,
    countInStock: 5,
    description: 'Ibanez J Custom RG8527 7-String Electric Guitar with Case',
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: 'Ibanez RGDR4327 RGD Prestige',
    slug: 'ibanez-rgdr4327-rgd-prestige',
    image: '../images/p2.jpg',
    brand: 'Ibanez',
    price: 1999.99,
    countInStock: 7,
    description:
      'Ibanez RGDR4327 RGD Prestige 7-String Electric Guitar with Case',
    rating: 4.0,
    numReviews: 8,
  },
  {
    name: 'IBANEZ SR1355BDUF 5 STRING BASS',
    slug: 'ibanez-sr1355bduf-5-string-bass',
    image: '../images/p3.jpg',
    brand: 'Ibanez',
    price: 1999.99,
    countInStock: 11,
    description: 'IBANEZ SR1355BDUF 5 STRING BASS',
    rating: 4.8,
    numReviews: 12,
  },
  {
    name: 'Ibanez Gio GSR206SMNGT Bass Guitar',
    slug: 'ibanez-gio-gsr206smngt-bass-guitar',
    image: '../images/p4.jpg',
    brand: 'Ibanez',
    price: 299.99,
    countInStock: 7,
    description: 'Ibanez Gio GSR206SMNGT Bass Guitar',
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: 'Fractal Audio FM3 Turbo',
    slug: 'fractal-audio-fm3-turbo',
    image: '../images/p5.jpg',
    brand: 'Fractal Audio',
    price: 999.99,
    countInStock: 11,
    description: 'Fractal Audio FM3 Turbo Modeling Amp/FX Processor',
    rating: 4.8,
    numReviews: 12,
  },
  {
    name: 'Neural DSP Quad Cortex',
    slug: 'neural-dsp-quad-cortex',
    image: '../images/p6.jpg',
    brand: 'Neural DSP',
    price: 1499.99,
    countInStock: 7,
    description: 'Neural DSP Quad Cortex Modeling Amp/FX Processor',
    rating: 4.5,
    numReviews: 10,
  },
];
